"""empty message

Revision ID: 388551b3fc78
Revises: 7fc9e4530d6b
Create Date: 2025-05-31 16:38:13.477107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388551b3fc78'
down_revision = '7fc9e4530d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id,', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id,'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tags')
    # ### end Alembic commands ###
