"""empty message

Revision ID: 532e730bfb50
Revises: 388551b3fc78
Create Date: 2025-06-03 09:05:21.550010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532e730bfb50'
down_revision = '388551b3fc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('posts_tags', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.create_foreign_key(None, 'posts_tags', 'tag', ['tag_id'], ['id'])
    op.drop_column('posts_tags', 'tag_id,')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_tags', sa.Column('tag_id,', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.create_foreign_key(None, 'posts_tags', 'tag', ['tag_id,'], ['id'])
    op.drop_column('posts_tags', 'tag_id')
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
